//USER REQUESTS



//add a user
POST http://localhost:4000/users
Content-Type: application/json

# {
#     "userName":"Samuel Ndambuki",
#     "email":"sam.ndambuki@outlook.com",
#     "password":"N10234424008s"
# }

# {
#     "userName":"Samuel Ndambuki",
#     "email":"samuelndambuki401@gmail.com",
#     "password":"N10234424008s"
# }

{
    "userName":"Esther Muchoki",
    "email":"muchokiesther8@gmail.com",
    "password":"Mesther1"
}


###
//gets all users
GET http://localhost:4000/users

###
//gets user by id
GET http://localhost:4000/users/bee2f213-39d2-42a3-990c-f9836fbb848e

###
//update users
PUT http://localhost:4000/users/bee2f213-39d2-42a3-990c-f9836fbb848e
Content-Type: application/json

{
    "userName":"Samuel Ndambuki",
    "email":"sam.ndambuki@outlook.com.com",
    "password":"N10234424008s"
}

###
//delete a user
DELETE http://localhost:4000/users/6edc3b33-8de6-497c-9fc1-4bd17c624a29






###
//TAG REQUESTS
//add a tag
POST http://localhost:4000/tags
Content-Type: application/json

{
    "tagName":"Java"
}

###
//get all tags
GET http://localhost:4000/tags

###
//get tag by id
GET http://localhost:4000/tags/240e474a-4969-4592-84fd-0d2743674366

###
//update a specific tag
PUT http://localhost:4000/tags/1a1b6a3c-9738-4ae8-8a4b-266c52622036
Content-Type: application/json

{
    "tagName":"Typescript"
}

###
//delete a specific tag
DELETE http://localhost:4000/tags/1a1b6a3c-9738-4ae8-8a4b-266c52622036





###
//ANSWER REQUESTS
//add an answer
POST http://localhost:4000/answers
Content-Type: application/json

{
    "userId":"",
    "questionId":"",
    "body":"",
    "createdAt":"",
    " updatedAt":"",
    "upVote":"",
    "downVote":"",
}


###
//get all answers
GET http://localhost:4000/answers

###
//get answer by id
GET http://localhost:4000/answers/bee2f213-39d2-42a3-990c-f9836fbb848e

###
//update answer
PUT http://localhost:4000/users/bee2f213-39d2-42a3-990c-f9836fbb848e
Content-Type: application/json

{
    "userId":"",
    "questionId":"",
    "body":"",
    "createdAt":"",
    " updatedAt":"",
    "upVote":"",
    "downVote":"",
}

###
//delete an answer
DELETE http://localhost:4000/answers/6edc3b33-8de6-497c-9fc1-4bd17c624a29






###
# QUESTION ROUTES
//adds a question
POST http://localhost:4000/QUESTIONS
Content-Type: application/json

{
    "userId":"",
    "title":"",
    "details":"",
    "tried":"",
    "tags":""
}

###
//gets all questions
GET http://localhost:4000/questions

###
//gets question by id
GET http://localhost:4000/questions/bee2f213-39d2-42a3-990c-f9836fbb848e

###
//updates a specific question
PUT http://localhost:4000/questions/bee2f213-39d2-42a3-990c-f9836fbb848e
Content-Type: application/json

{
    "userId":"",
    "title":"",
    "details":"",
    "tried":"",
    "tags":""
}


###
//deletes a specific question
DELETE http://localhost:4000/questions/6edc3b33-8de6-497c-9fc1-4bd17c624a29


###
# COMMENTS REQUEST
//add a comment
POST http://localhost:4000/comments
Content-Type: application/json

{
    "userId":"",
    "questionId":"",
    "answerId":"",
    "body":""
}

###

//update a comment comments/comment id
PUT http://localhost:4000/comments/bee2f213-39d2-42a3-990c-f9836fbb848e
Content-Type: application/json

{
    "body":"",
}


###
//get all comments
GET http://localhost:4000/comments

###
//get comment by comment id /comments/comment id
GET http://localhost:4000/comments/bee2f213-39d2-42a3-990c-f9836fbb848e

###
//get comment by question id /comments/questionId
GET http://localhost:4000/comments/bee2f213-39d2-42a3-990c-f9836fbb848e

###
//get comment by answer id /comments/answerId
GET http://localhost:4000/comments/bee2f213-39d2-42a3-990c-f9836fbb848e

###
//delete a comment /comments/comment id
DELETE http://localhost:4000/comments/6edc3b33-8de6-497c-9fc1-4bd17c624a29




###
# QUESTION TAG REQUESTS
//add question tag
POST http://localhost:4000/questionTags
Content-Type: application/json

{
    "questionId": "123456",
    "tagId": "789012"
}

//update a question tag
PUT http://localhost:4000/questionTags/questionTag/123456/789012
Content-Type: application/json

{
    "newTagId": ""
}

###
//get all question tags
GET http://localhost:4000/questionTags

###
//get question tags by tag id
GET http://localhost:4000/questionTags/questionTag/789012

###
//get question tags by question id
GET http://localhost:4000/questionTags/questionTag/123456


###
//delete a question tag
DELETE http://localhost:4000/questionTags/questionTag/123456/789012

