//USER REQUESTS

//add a user
POST http://localhost:4000/users
Content-Type: application/json

# {
#     "userName":"Samuel Ndambuki",
#     "email":"techflux6@gmail.com",
#     "password":"N10234424008s"
# }


{
    "userName":"admin",
    "email":"samuelndambuki401@gmail.com",
    "password":"N10238114040s",
    "isAdmin":"true"
}





###
//gets all users
GET http://localhost:4000/users
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMzRiYzBhZC01ZjA0LTQxYTEtYTdkYi1hZjVmOThjNGRmMTkiLCJ1c2VyTmFtZSI6ImFkbWluIiwiZW1haWwiOiJzYW11ZWxuZGFtYnVraTQwMUBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTA2LTIwVDE2OjQwOjAwLjAwMFoiLCJ1cGRhdGVkQXQiOm51bGwsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjoxLCJpYXQiOjE2ODcyNjk3NjIsImV4cCI6MTY4NzYyOTc2Mn0.vi22JzU_00aVqqXEXN9xHRXNBqQfV09H68-UNzxWWOA

###
//gets user by id
GET http://localhost:4000/users/9ec4f077-e521-498a-8954-d6cbcef84230
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ZWM0ZjA3Ny1lNTIxLTQ5OGEtODk1NC1kNmNiY2VmODQyMzAiLCJ1c2VyTmFtZSI6IlNhbXVlbCBOZGFtYnVraSIsImVtYWlsIjoidGVjaGZsdXg2QGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDYtMjBUMTY6Mzk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6bnVsbCwiZW1haWxTZW50IjowLCJpc0RlbGV0ZWQiOjAsImlzQWRtaW4iOjAsImlhdCI6MTY4NzI2OTgyOSwiZXhwIjoxNjg3NjI5ODI5fQ.hcHsVaYYcZ6khpShyn4NYcF0Is-o8tyzlgNIibJUawM

###
//update users
PUT http://localhost:4000/users/9ec4f077-e521-498a-8954-d6cbcef84230
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ZWM0ZjA3Ny1lNTIxLTQ5OGEtODk1NC1kNmNiY2VmODQyMzAiLCJ1c2VyTmFtZSI6IlNhbXVlbCBOZGFtYnVraSIsImVtYWlsIjoidGVjaGZsdXg2QGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDYtMjBUMTY6Mzk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6bnVsbCwiZW1haWxTZW50IjowLCJpc0RlbGV0ZWQiOjAsImlzQWRtaW4iOjAsImlhdCI6MTY4NzI3MDI0NSwiZXhwIjoxNjg3NjMwMjQ1fQ.wymK_rFQ6xTGB_48q7DnFWHmgeqTLnN8AeTD43y4Iac

{
    "userName":"Samuel Ndambuki",
    "email":"techflux6@gmail.com",
    "password":"N10234424008s"
}

###
//delete a user
DELETE http://localhost:4000/users/6edc3b33-8de6-497c-9fc1-4bd17c624a29
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ZWM0ZjA3Ny1lNTIxLTQ5OGEtODk1NC1kNmNiY2VmODQyMzAiLCJ1c2VyTmFtZSI6IlNhbXVlbCBOZGFtYnVraSIsImVtYWlsIjoidGVjaGZsdXg2QGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDYtMjBUMTY6Mzk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6bnVsbCwiZW1haWxTZW50IjowLCJpc0RlbGV0ZWQiOjAsImlzQWRtaW4iOjAsImlhdCI6MTY4NzI2OTY3MSwiZXhwIjoxNjg3NjI5NjcxfQ.17zo1JJlKKrF2TpZ56czVAupj9gzrJbitHAGkJSduY4


####
//log in user
POST http://localhost:4000/users/login
Content-Type: application/json


 {
    "email":"techflux6@gmail.com",
    "password":"N10234424008s"
 }

#  {
#     "email":"samuelndambuki401@gmail.com",
#     "password":"N10238114040s"
#  }




###
//TAG REQUESTS
//add a tag
POST http://localhost:4000/tags
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ZWM0ZjA3Ny1lNTIxLTQ5OGEtODk1NC1kNmNiY2VmODQyMzAiLCJ1c2VyTmFtZSI6IlNhbXVlbCBOZGFtYnVraSIsImVtYWlsIjoidGVjaGZsdXg2QGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDYtMjBUMTY6Mzk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDYtMjBUMjE6MjI6MTQuMDAwWiIsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjowLCJpYXQiOjE2ODcyODUzNDcsImV4cCI6MTY4NzY0NTM0N30.jr0qmcdN_cu_0Tdf0J2PnpQ5hpnUA72AHRnNajMuBVY


{
    "tagName":"Python"
}

###
//get all tags
GET http://localhost:4000/tags
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ZWM0ZjA3Ny1lNTIxLTQ5OGEtODk1NC1kNmNiY2VmODQyMzAiLCJ1c2VyTmFtZSI6IlNhbXVlbCBOZGFtYnVraSIsImVtYWlsIjoidGVjaGZsdXg2QGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDYtMjBUMTY6Mzk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDYtMjBUMjE6MjI6MTQuMDAwWiIsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjowLCJpYXQiOjE2ODcyODUzNDcsImV4cCI6MTY4NzY0NTM0N30.jr0qmcdN_cu_0Tdf0J2PnpQ5hpnUA72AHRnNajMuBVY

###
//get tag by id
GET http://localhost:4000/tags/240e474a-4969-4592-84fd-0d2743674366
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ZWM0ZjA3Ny1lNTIxLTQ5OGEtODk1NC1kNmNiY2VmODQyMzAiLCJ1c2VyTmFtZSI6IlNhbXVlbCBOZGFtYnVraSIsImVtYWlsIjoidGVjaGZsdXg2QGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDYtMjBUMTY6Mzk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDYtMjBUMjE6MjI6MTQuMDAwWiIsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjowLCJpYXQiOjE2ODcyODUzNDcsImV4cCI6MTY4NzY0NTM0N30.jr0qmcdN_cu_0Tdf0J2PnpQ5hpnUA72AHRnNajMuBVY


###
//update a specific tag
PUT http://localhost:4000/tags/240e474a-4969-4592-84fd-0d2743674366
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMzRiYzBhZC01ZjA0LTQxYTEtYTdkYi1hZjVmOThjNGRmMTkiLCJ1c2VyTmFtZSI6ImFkbWluIiwiZW1haWwiOiJzYW11ZWxuZGFtYnVraTQwMUBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTA2LTIwVDE2OjQwOjAwLjAwMFoiLCJ1cGRhdGVkQXQiOm51bGwsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjoxLCJpYXQiOjE2ODcyODY0NzEsImV4cCI6MTY4NzY0NjQ3MX0.-mNvT0FL7-l7Yz5NEOCdE5tdbM8Gapt9_nMng_5I_bM

{
    "tagName":"Typescript"
}

###
//delete a specific tag
DELETE http://localhost:4000/tags/240e474a-4969-4592-84fd-0d2743674366
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ZWM0ZjA3Ny1lNTIxLTQ5OGEtODk1NC1kNmNiY2VmODQyMzAiLCJ1c2VyTmFtZSI6IlNhbXVlbCBOZGFtYnVraSIsImVtYWlsIjoidGVjaGZsdXg2QGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDYtMjBUMTY6Mzk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDYtMjBUMjE6MjI6MTQuMDAwWiIsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjowLCJpYXQiOjE2ODcyODUzNDcsImV4cCI6MTY4NzY0NTM0N30.jr0qmcdN_cu_0Tdf0J2PnpQ5hpnUA72AHRnNajMuBVY




####

###
# QUESTION ROUTES
//ask a question
POST http://localhost:4000/questions
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMzRiYzBhZC01ZjA0LTQxYTEtYTdkYi1hZjVmOThjNGRmMTkiLCJ1c2VyTmFtZSI6ImFkbWluIiwiZW1haWwiOiJzYW11ZWxuZGFtYnVraTQwMUBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTA2LTIwVDE2OjQwOjAwLjAwMFoiLCJ1cGRhdGVkQXQiOm51bGwsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjoxLCJpYXQiOjE2ODcyODY5MzQsImV4cCI6MTY4NzY0NjkzNH0.hCtTxAumk_Wq3Qxk5931-7KjG-Tm_uIla0DHHglAYLY

{
    "userId":"9ec4f077-e521-498a-8954-d6cbcef84230",
    "title":"question1 ",
    "details":"this is question 1",
    "tried":"I tried question 1",
    "tags":"Javascript"
}

###
//gets all questions
GET http://localhost:4000/questions
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMzRiYzBhZC01ZjA0LTQxYTEtYTdkYi1hZjVmOThjNGRmMTkiLCJ1c2VyTmFtZSI6ImFkbWluIiwiZW1haWwiOiJzYW11ZWxuZGFtYnVraTQwMUBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTA2LTIwVDE2OjQwOjAwLjAwMFoiLCJ1cGRhdGVkQXQiOm51bGwsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjoxLCJpYXQiOjE2ODcyODc1MjAsImV4cCI6MTY4NzY0NzUyMH0.cN9dKozEsZxiBY_vfP256BUYEprQIso4WvsfuEm7PWs

###
//gets question by id
GET http://localhost:4000/questions/00898f6b-4fd1-4479-9f09-9b462c44cf0f
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMzRiYzBhZC01ZjA0LTQxYTEtYTdkYi1hZjVmOThjNGRmMTkiLCJ1c2VyTmFtZSI6ImFkbWluIiwiZW1haWwiOiJzYW11ZWxuZGFtYnVraTQwMUBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTA2LTIwVDE2OjQwOjAwLjAwMFoiLCJ1cGRhdGVkQXQiOm51bGwsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjoxLCJpYXQiOjE2ODcyODc1MjAsImV4cCI6MTY4NzY0NzUyMH0.cN9dKozEsZxiBY_vfP256BUYEprQIso4WvsfuEm7PWs


###
//updates a specific question
PUT http://localhost:4000/questions/00898f6b-4fd1-4479-9f09-9b462c44cf0f
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMzRiYzBhZC01ZjA0LTQxYTEtYTdkYi1hZjVmOThjNGRmMTkiLCJ1c2VyTmFtZSI6ImFkbWluIiwiZW1haWwiOiJzYW11ZWxuZGFtYnVraTQwMUBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTA2LTIwVDE2OjQwOjAwLjAwMFoiLCJ1cGRhdGVkQXQiOm51bGwsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjoxLCJpYXQiOjE2ODcyODc1MjAsImV4cCI6MTY4NzY0NzUyMH0.cN9dKozEsZxiBY_vfP256BUYEprQIso4WvsfuEm7PWs

{
    "title":"javascript error",
    "details":"reference error",
    "tried":"console.log(variablename)",
    "tags":"javascript"
}


###
//deletes a specific question
DELETE http://localhost:4000/questions/00898f6b-4fd1-4479-9f09-9b462c44cf0f
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMzRiYzBhZC01ZjA0LTQxYTEtYTdkYi1hZjVmOThjNGRmMTkiLCJ1c2VyTmFtZSI6ImFkbWluIiwiZW1haWwiOiJzYW11ZWxuZGFtYnVraTQwMUBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDIzLTA2LTIwVDE2OjQwOjAwLjAwMFoiLCJ1cGRhdGVkQXQiOm51bGwsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjoxLCJpYXQiOjE2ODcyODc1MjAsImV4cCI6MTY4NzY0NzUyMH0.cN9dKozEsZxiBY_vfP256BUYEprQIso4WvsfuEm7PWs


###
//deletes all questions
DELETE http://localhost:4000/questions
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ZWM0ZjA3Ny1lNTIxLTQ5OGEtODk1NC1kNmNiY2VmODQyMzAiLCJ1c2VyTmFtZSI6IlNhbXVlbCBOZGFtYnVraSIsImVtYWlsIjoidGVjaGZsdXg2QGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDYtMjBUMTY6Mzk6NDEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDYtMjBUMjE6MjI6MTQuMDAwWiIsImVtYWlsU2VudCI6MCwiaXNEZWxldGVkIjowLCJpc0FkbWluIjowLCJpYXQiOjE2ODcyODg4NTUsImV4cCI6MTY4NzY0ODg1NX0.MEUiKg21iDS53lgOz3Yz14kgHmysgxiW24s9nTwMHW8







###
//ANSWER REQUESTS
//add an answer
POST http://localhost:4000/answers
Content-Type: application/json
token:

{
    "userId":"",
    "questionId":"",
    "body":"",
    "createdAt":"",
    " updatedAt":"",
    "upVote":"",
    "downVote":"",
}


###
//get all answers
GET http://localhost:4000/answers

###
//get answer by id
GET http://localhost:4000/answers/bee2f213-39d2-42a3-990c-f9836fbb848e

###
//update answer
PUT http://localhost:4000/users/bee2f213-39d2-42a3-990c-f9836fbb848e
Content-Type: application/json

{
    "userId":"",
    "questionId":"",
    "body":"",
    "createdAt":"",
    " updatedAt":"",
    "upVote":"",
    "downVote":"",
}

###
//delete an answer
DELETE http://localhost:4000/answers/6edc3b33-8de6-497c-9fc1-4bd17c624a29







###
# COMMENTS REQUEST
//add a comment
POST http://localhost:4000/comments
Content-Type: application/json

{
    "userId":"",
    "questionId":"",
    "answerId":"",
    "body":""
}

###

//update a comment comments/comment id
PUT http://localhost:4000/comments/bee2f213-39d2-42a3-990c-f9836fbb848e
Content-Type: application/json

{
    "body":"",
}


###
//get all comments
GET http://localhost:4000/comments

###
//get comment by comment id /comments/comment id
GET http://localhost:4000/comments/bee2f213-39d2-42a3-990c-f9836fbb848e

###
//get comment by question id /comments/questionId
GET http://localhost:4000/comments/bee2f213-39d2-42a3-990c-f9836fbb848e

###
//get comment by answer id /comments/answerId
GET http://localhost:4000/comments/bee2f213-39d2-42a3-990c-f9836fbb848e

###
//delete a comment /comments/comment id
DELETE http://localhost:4000/comments/6edc3b33-8de6-497c-9fc1-4bd17c624a29




###
# QUESTION TAG REQUESTS
//add question tag
POST http://localhost:4000/questionTags
Content-Type: application/json

{
    "questionId": "123456",
    "tagId": "789012"
}

//update a question tag
PUT http://localhost:4000/questionTags/questionTag/123456/789012
Content-Type: application/json

{
    "newTagId": ""
}

###
//get all question tags
GET http://localhost:4000/questionTags

###
//get question tags by tag id
GET http://localhost:4000/questionTags/questionTag/789012

###
//get question tags by question id
GET http://localhost:4000/questionTags/questionTag/123456


###
//delete a question tag
DELETE http://localhost:4000/questionTags/questionTag/123456/789012





# VOTES REQUESTS
####
//upvote an asnwer
POST http://localhost:4000/votes/upvote
Content-Type: application/json


//downvote an asnwer
POST http://localhost:4000/votes/upvote
Content-Type: application/json

